### ISSUE TITLE
NAnt script issue

### ISSUE THREAD

**Issue by JKSnd** [LeeSanderson/Concurrency#1]
When running the concurrency.build script, the build fails with a "failed to register" error. Have you seen this before?

     [exec] Failed to register(user:True,register:True,is64:True):3 the profiler assembly; you may want to look into permissions or using the -register:user option instead. C:\Windows\system32\regsvr32.exe /s  /n /i:user "C:\Dev\chessConcurrency\packages\OpenCover.4.6.519\tools\x64\OpenCover.Profiler.dll"
     [exec] If you are unable to resolve the issue please contact the OpenCover development team
     [exec] see https://www.github.com/opencover/opencover/issues

**Comment by LeeSanderson** [comment]
This is an OpenCover issue (see https://github.com/OpenCover/opencover/issues/557 for possible solutions ). 

Alternatively you can just run the "build" or "chess" nant tasks - as only the "test" nant task relies uses OpenCover.
